### ISSUE TITLE
Scripts in demo/ does not work in wxPython Phoenix / Python 3

### ISSUE THREAD

**Issue by Leon0824** [AndersMunch/wxWize#1]
# demo/demo_custom.py
`ModuleNotFoundError: No module named 'wx.gizmos'`

Module wx.gizmos is not implemented to wxPython Phoenix yet.

# demo/demo_simple.py
`NameError: name 'xrange' is not defined`

xrange is replaced by range in Python 3.

**Comment by AndersMunch** [comment]
Fixed in 1.0.3
